// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Sigmoid
NumericVector Sigmoid(NumericVector a, double n, double k);
RcppExport SEXP _LinQseq_Sigmoid(SEXP aSEXP, SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(Sigmoid(a, n, k));
    return rcpp_result_gen;
END_RCPP
}
// EucNorm
double EucNorm(NumericVector a);
RcppExport SEXP _LinQseq_EucNorm(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(EucNorm(a));
    return rcpp_result_gen;
END_RCPP
}
// scaleDistCpp
NumericMatrix scaleDistCpp(NumericMatrix data, double n, double k);
RcppExport SEXP _LinQseq_scaleDistCpp(SEXP dataSEXP, SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleDistCpp(data, n, k));
    return rcpp_result_gen;
END_RCPP
}
// objectiveFunctionCpp
double objectiveFunctionCpp(double alpha, NumericVector X, NumericVector Y);
RcppExport SEXP _LinQseq_objectiveFunctionCpp(SEXP alphaSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(objectiveFunctionCpp(alpha, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// gradientFunctionCpp
double gradientFunctionCpp(double alpha, NumericVector X, NumericVector Y);
RcppExport SEXP _LinQseq_gradientFunctionCpp(SEXP alphaSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(gradientFunctionCpp(alpha, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// gradientDescentCpp
double gradientDescentCpp(NumericVector X, NumericVector Y, double alpha, double learning_rate, double low_threshold, int max_iter);
RcppExport SEXP _LinQseq_gradientDescentCpp(SEXP XSEXP, SEXP YSEXP, SEXP alphaSEXP, SEXP learning_rateSEXP, SEXP low_thresholdSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< double >::type low_threshold(low_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(gradientDescentCpp(X, Y, alpha, learning_rate, low_threshold, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LinQseq_Sigmoid", (DL_FUNC) &_LinQseq_Sigmoid, 3},
    {"_LinQseq_EucNorm", (DL_FUNC) &_LinQseq_EucNorm, 1},
    {"_LinQseq_scaleDistCpp", (DL_FUNC) &_LinQseq_scaleDistCpp, 3},
    {"_LinQseq_objectiveFunctionCpp", (DL_FUNC) &_LinQseq_objectiveFunctionCpp, 3},
    {"_LinQseq_gradientFunctionCpp", (DL_FUNC) &_LinQseq_gradientFunctionCpp, 3},
    {"_LinQseq_gradientDescentCpp", (DL_FUNC) &_LinQseq_gradientDescentCpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_LinQseq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
