# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call(`_LinQseq_timesTwo`, x)
}

#' Sigmoid function
#'
#' @param a A Numeric Vector. original distance
#' @param n n for Sigmoid function.
#' @param k k for Sigmoid function.
#' @export
Sigmoid <- function(a, n, k) {
    .Call(`_LinQseq_Sigmoid`, a, n, k)
}

#' EucNorm function
#'
#' @param a A Numeric Vector.
#' @export
EucNorm <- function(a) {
    .Call(`_LinQseq_EucNorm`, a)
}

#' Scale distance using a sigmoid function. The main purpose is to reduce the effects of small distances (those distances are most likely from random noise of ADT signals)
#'
#' @param data data matrix of ADT.
#' @param n n for Sigmoid function.
#' @param k k for Sigmoid function.
#' @export
scaleDistCpp <- function(data, n, k) {
    .Call(`_LinQseq_scaleDistCpp`, data, n, k)
}

