# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sigmoid function
#'
#' @param a A Numeric Vector. original distance
#' @param n n for Sigmoid function.
#' @param k k for Sigmoid function.
#' @export
Sigmoid <- function(a, n, k) {
    .Call(`_LinQseq_Sigmoid`, a, n, k)
}

#' EucNorm function
#'
#' @param a A Numeric Vector.
#' @export
EucNorm <- function(a) {
    .Call(`_LinQseq_EucNorm`, a)
}

#' Scale distance using a sigmoid function. The main purpose is to reduce the effects of small distances (those distances are most likely from random noise of ADT signals)
#'
#' @param data data matrix of ADT.
#' @param n n for Sigmoid function.
#' @param k k for Sigmoid function.
#' @export
scaleDistCpp <- function(data, n, k) {
    .Call(`_LinQseq_scaleDistCpp`, data, n, k)
}

#' objective function for gradient descnet method
#'
#' @param alpha current value of parameter alpha.
#' @param X distance vector.
#' @param Y distance vector.
#' @export
objectiveFunctionCpp <- function(alpha, X, Y) {
    .Call(`_LinQseq_objectiveFunctionCpp`, alpha, X, Y)
}

#' gradient function for gradient descnet method
#'
#' @param alpha current value of parameter alpha.
#' @param X distance vector.
#' @param Y distance vector.
#' @export
gradientFunctionCpp <- function(alpha, X, Y) {
    .Call(`_LinQseq_gradientFunctionCpp`, alpha, X, Y)
}

#' gradient descnet method
#'
#' @param X distance vector.
#' @param Y distance vector.
#' @param alpha initial value of parameter alpha.
#' @param learning_rate learning rate of GD method
#' @param low_threshold the low threshold of GD
#' @param max_iter maximum iterations
#' @export
gradientDescentCpp <- function(X, Y, alpha, learning_rate, low_threshold, max_iter) {
    .Call(`_LinQseq_gradientDescentCpp`, X, Y, alpha, learning_rate, low_threshold, max_iter)
}

